"""Made a relationship between a user and posts

Revision ID: 778a348f8bd6
Revises: f2f5acc20722
Create Date: 2024-10-15 11:03:40.771816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778a348f8bd6'
down_revision = 'f2f5acc20722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
